### ISSUE TITLE
expose series_id

### ISSUE THREAD

**Issue by diodon** [AIMS/data-platform-r#11]
In temp_loggers, it would be useful to expose site_id. Sometìmes is better to work programmatically with the ids than with names. 

Like: 

```
gb <- aims_data(ssts_doi,
                        filters = list(site_id = 923,  ##Geoffrey Bay
                                       from_date = "2020-01-01",
                                       thru_date = "2020-02-28"))

```

**Comment by dbarneche** [comment]
Thanks @diodon That is also an issue for the Data Centre team I'm afraid.
This should be an output of the function `filter_values`. Could you ask Duncan to implement this such that the output of `filter_values` for `site` becomes similar to that of `series`, i.e. a two-column data.frame, one containing the ID, and the other the name?
