### ISSUE TITLE
replace subsite by location

### ISSUE THREAD

**Issue by diodon** [AIMS/data-platform-r#12]
Although `subsite` makes sense in the context of the data structure, `location` is the term used by researchers. I guess is it even coded that way in the database. It usually refers to reef flat (FL) or reef slope (SL) or channel (CH), and it is coded in the `location` (`subsite`) name (e.g. AG3FL1 or DAVSL1). Logger's program from WA frequently fails to put the reef location in the location field but those in the GBR all have it.

**Comment by dbarneche** [comment]
Thanks @diodon, also an issue for the Data Centre, as in the API side of things. This is not something we can resolve from the R package side of things.
