### ISSUE TITLE
More information returned by getFilterValues(doi, 'series')

### ISSUE THREAD

**Issue by diodon** [AIMS/data-platform-r#2]
it would be very useful if the `getFilterValues(doi, 'series') ` call could return more information about the site. in addition to the current returned fields `series_id` and `series_name` it would be desirable to have: 
`site_name`
`parameter_name`
`depth`
`from_date` (first record available)
`thru_date` (last record available)

With that it will be very easy to make the right API call (filters=) for the desired data only.

Cheers, EKS

BTW, very nice API!!!

**Comment by jlsheehan** [comment]
Hi!

Thanks very much for your feedback.  I'll try to get something onto a sprint soon.

Regards,

Jeff S
