### ISSUE TITLE
Server limit

### ISSUE THREAD

**Issue by diodon** [AIMS/data-platform-r#9]
I'm requesting data for many sites in a loop and at some point I got: 
`Error Client error Limit ExceededError Too Many Requests (RFC 6585) Limit ExceededError Client error: (429) Too Many Requests (RFC 6585) Limit Exceeded`

What is the limit of the server?
Thanks! EKS

**Comment by dbarneche** [comment]
Thanks @diodon and apologies for taking so long to reply. Mark is on the case as this is something to be tackled on the API side. I hope it's OK with you, but I'll close this issue
